package org.frameworkset.util.annotations;

public enum Scope {
	REQUEST_PARAM,SESSION_ATTRIBUTE,REQUEST_ATTRIBUTE,PAGECONTEXT_PAGE_SCOPE,PAGECONTEXT_REQUEST_SCOPE,PAGECONTEXT_SESSION_SCOPE
	,PAGECONTEXT_APPLICATION_SCOPE,MODEL_ATTRIBUTE
	,PATHVARIABLE
	,COOKIE
	,REQUEST_HEADER
	,REQUEST_BODY
	,PAGER_PARAM
	,MAP_PARAM
}
