package org.frameworkset.spi.remote.wsclient;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import org.apache.cxf.jaxws.spi.ProviderImpl;
import org.apache.cxf.service.model.EndpointInfo;
import org.apache.cxf.service.model.ServiceInfo;
import org.apache.cxf.transport.http.HTTPTransportFactory;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-11-12T14:21:57.265+08:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "ZWS_FI_FYKZ_V1", 
                  wsdlLocation = "ZWSFIFYKZV1.wsdl",
                  targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style") 
public class ZWSFIFYKZV1_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZWS_FI_FYKZ_V1");
    public final static QName ZWSFIFYKZV1 = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZWS_FI_FYKZ_V1");
    static {
        URL url = ZWSFIFYKZV1_Service.class.getResource("ZWSFIFYKZV1.wsdl");
        if (url == null) {
            url = ZWSFIFYKZV1_Service.class.getClassLoader().getResource("ZWSFIFYKZV1.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(ZWSFIFYKZV1_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "ZWSFIFYKZV1.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public ZWSFIFYKZV1_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ZWSFIFYKZV1_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZWSFIFYKZV1_Service() {
        super(WSDL_LOCATION, SERVICE);
        

        

    }
    

    /**
     *
     * @return
     *     returns ZWSFIFYKZV1
     */
    @WebEndpoint(name = "ZWS_FI_FYKZ_V1")
    public ZWSFIFYKZV1 getZWSFIFYKZV1() {
        return super.getPort(ZWSFIFYKZV1, ZWSFIFYKZV1.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZWSFIFYKZV1
     */
    @WebEndpoint(name = "ZWS_FI_FYKZ_V1")
    public ZWSFIFYKZV1 getZWSFIFYKZV1(WebServiceFeature... features) {
        return super.getPort(ZWSFIFYKZV1, ZWSFIFYKZV1.class, features);
    }

}
