global
    log         127.0.0.1 local2

    chroot      /usr/local/haproxy
    pidfile     /usr/local/haproxy/logs/haproxy.pid
    maxconn     4000
    daemon

    # turn on stats unix socket
    stats socket /usr/local/haproxy/stats

defaults
    mode                    http
    log                     global
    option                  httplog
    option                  dontlognull
    option http-server-close
    option forwardfor       except 127.0.0.0/8
    option                  redispatch
    retries                 3
    timeout http-request    10s
    timeout queue           1m
    timeout connect         10s
    timeout client          1m
    timeout server          1m
    timeout http-keep-alive 10s
    timeout check           10s
    maxconn                 3000

#---------------------------------------------------------------------
# main frontend which proxys to the backends
#---------------------------------------------------------------------
frontend  main *:80
#    acl url_static       path_beg       -i /static /images /javascript /stylesheets
#   acl url_static       path_end       -i .jpg .gif .png .css .js
#    use_backend static          if url_static

    default_backend             app

#---------------------------------------------------------------------
# static backend for serving up images, stylesheets and such
#---------------------------------------------------------------------

#backend static
#    balance     roundrobin
#    server      static 127.0.0.1:4331 check

#---------------------------------------------------------------------
# round robin balancing between the various backends
#---------------------------------------------------------------------
backend app
    balance     roundrobin
#	option httpchk GET /index.html
	#option httpchk HEAD /SanyPDP/detail.html
    # option httpchk HEAD /SanyPDP/detail.html HTTP/1.1
#option httpchk GET /detail.html HTTP/1.1
#    server  app1 192.168.137.128:80 check
#    server  app2 192.168.137.129:80 check
	server  s1 10.0.15.38:9081  cookie 1 weight 1 check inter 5s rise 2 fall 3
	server  s2 10.25.192.142:8080 cookie 1 weight 1 check inter 5s rise 2 fall 3
#	server  s3 192.168.148.110:8081 cookie 1 weight 1 check inter 5s rise 2 fall 3

#    server  app3 127.0.0.1:5003 check
#    server  app4 127.0.0.1:5004 check
listen status
    bind *:1158                
    mode http                        
    stats refresh 10s 
    stats uri /haproxy 
    stats realm Haproxy\ Statistics
    stats auth admin:admin
    stats hide-version 
stats admin if TRUE
