package org.frameworkset.spi.remote.wsclient1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-11-12T15:00:44.749+08:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "org.frameworkset.web.ws", name = "WSService")
@XmlSeeAlso({ObjectFactory.class})
public interface WSService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "org.frameworkset.web.ws", className = "org.frameworkset.spi.remote.wsclient1.SayHello")
    @WebMethod
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "org.frameworkset.web.ws", className = "org.frameworkset.spi.remote.wsclient1.SayHelloResponse")
    public java.lang.String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
