GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'ok' WITH      GRANT OPTION;
CREATE TABLE
    TABLEINFO
    (
        TABLE_NAME VARCHAR(255) NOT NULL,
        TABLE_ID_NAME VARCHAR(255),
        TABLE_ID_INCREMENT INTEGER DEFAULT 1,
        TABLE_ID_VALUE INTEGER DEFAULT 0,
        TABLE_ID_GENERATOR VARCHAR(255),
        TABLE_ID_TYPE VARCHAR(255),
        TABLE_ID_PREFIX VARCHAR(255),
        PRIMARY KEY (TABLE_NAME)
    );
    CREATE TABLE
    TB_USER
    (
        USERID BIGINT NOT NULL,
        USERNAME VARCHAR(100),
        USERPASSWORD VARCHAR(100),
        PRIMARY KEY (USERID)
    );
    CREATE TABLE
    LISTBEAN
    (
        ID INTEGER NOT NULL,
        FIELDNAME VARCHAR(300),
        FIELDLABLE VARCHAR(300),
        FIELDTYPE VARCHAR(300),
        SORTORDER VARCHAR(300),
        ISPRIMARYKEY INTEGER,
        REQUIRED INTEGER,
        FIELDLENGTH INTEGER,
        ISVALIDATED INTEGER,
        CONSTRAINT LISTBEANKEY PRIMARY KEY (ID)
    );
    CREATE TABLE
    FILETABLE
    (
        FILENAME VARCHAR(100),
        FILECONTENT BLOB(2147483647)
    );
insert into TABLEINFO (TABLE_NAME, TABLE_ID_NAME, TABLE_ID_INCREMENT, TABLE_ID_VALUE, TABLE_ID_GENERATOR, TABLE_ID_TYPE, TABLE_ID_PREFIX) values ('CIM_DATACACHE', 'CACHEID', 1, 1, null, 'uuid', null);
insert into TABLEINFO (TABLE_NAME, TABLE_ID_NAME, TABLE_ID_INCREMENT, TABLE_ID_VALUE, TABLE_ID_GENERATOR, TABLE_ID_TYPE, TABLE_ID_PREFIX) values ('CIM_ETL_REPOSITORY', 'ID', 1, 1, null, 'uuid', null);
insert into TABLEINFO (TABLE_NAME, TABLE_ID_NAME, TABLE_ID_INCREMENT, TABLE_ID_VALUE, TABLE_ID_GENERATOR, TABLE_ID_TYPE, TABLE_ID_PREFIX) values ('TB_USER', 'USERID', 1, 10, null, 'int', null);
insert into TABLEINFO (TABLE_NAME, TABLE_ID_NAME, TABLE_ID_INCREMENT, TABLE_ID_VALUE, TABLE_ID_GENERATOR, TABLE_ID_TYPE, TABLE_ID_PREFIX) values ('LISTBEAN', 'id', 1, 0, null, 'int', null);
