/* Generated By:JavaCC: Do not edit this line. StandardParserTreeConstants.java Version 7.0.13 */
package bboss.org.apache.velocity.runtime.parser.node;

import bboss.org.apache.velocity.runtime.parser.*;

public interface StandardParserTreeConstants
{
  public int JJTPROCESS = 0;
  public int JJTVOID = 1;
  public int JJTTEXT = 2;
  public int JJTESCAPEDDIRECTIVE = 3;
  public int JJTESCAPE = 4;
  public int JJTCOMMENT = 5;
  public int JJTTEXTBLOCK = 6;
  public int JJTFLOATINGPOINTLITERAL = 7;
  public int JJTINTEGERLITERAL = 8;
  public int JJTSTRINGLITERAL = 9;
  public int JJTIDENTIFIER = 10;
  public int JJTWORD = 11;
  public int JJTDIRECTIVEASSIGN = 12;
  public int JJTDIRECTIVE = 13;
  public int JJTBLOCK = 14;
  public int JJTMAP = 15;
  public int JJTOBJECTARRAY = 16;
  public int JJTINTEGERRANGE = 17;
  public int JJTMETHOD = 18;
  public int JJTINDEX = 19;
  public int JJTREFERENCE = 20;
  public int JJTTRUE = 21;
  public int JJTFALSE = 22;
  public int JJTIFSTATEMENT = 23;
  public int JJTELSESTATEMENT = 24;
  public int JJTELSEIFSTATEMENT = 25;
  public int JJTSETDIRECTIVE = 26;
  public int JJTEXPRESSION = 27;
  public int JJTASSIGNMENT = 28;
  public int JJTORNODE = 29;
  public int JJTANDNODE = 30;
  public int JJTEQNODE = 31;
  public int JJTNENODE = 32;
  public int JJTLTNODE = 33;
  public int JJTGTNODE = 34;
  public int JJTLENODE = 35;
  public int JJTGENODE = 36;
  public int JJTADDNODE = 37;
  public int JJTSUBTRACTNODE = 38;
  public int JJTMULNODE = 39;
  public int JJTDIVNODE = 40;
  public int JJTMODNODE = 41;
  public int JJTNOTNODE = 42;
  public int JJTNEGATENODE = 43;


  public String[] jjtNodeName = {
    "process",
    "void",
    "Text",
    "EscapedDirective",
    "Escape",
    "Comment",
    "Textblock",
    "FloatingPointLiteral",
    "IntegerLiteral",
    "StringLiteral",
    "Identifier",
    "Word",
    "DirectiveAssign",
    "Directive",
    "Block",
    "Map",
    "ObjectArray",
    "IntegerRange",
    "Method",
    "Index",
    "Reference",
    "True",
    "False",
    "IfStatement",
    "ElseStatement",
    "ElseIfStatement",
    "SetDirective",
    "Expression",
    "Assignment",
    "OrNode",
    "AndNode",
    "EQNode",
    "NENode",
    "LTNode",
    "GTNode",
    "LENode",
    "GENode",
    "AddNode",
    "SubtractNode",
    "MulNode",
    "DivNode",
    "ModNode",
    "NotNode",
    "NegateNode",
  };
}
/* JavaCC - OriginalChecksum=01e6f42db6247c8a3c1b20619c56251b (do not edit this line) */
